#!/bin/bash

for file in ../files/*; do
    if [ -f "$file" ]; then
        first_letter=$(basename "$file" | cut -c1 | tr '[:upper:]' '[:lower:]')

        if [ -d "../$first_letter" ]; then
          mv "$file" "../$first_letter/"
        fi
    fi
done
